pipeline {
    agent any 
    environment {
        APP_HOME = "/home/ubuntu/app"
        BACKEND_DIR = "backend"
        FRONTEND_DIR = "frontend"
    }

    stages{
        stage("Checkout"){
            steps {
                git(
                    url: "https://github.com/sanjay2028/ubuntu-tude-tude/",
                    branch: "jenkins"
                )
            }
        }

        stage("Backend"){
            steps {
                echo "Backend Process starts"
                sh """
                    echo "Kill the existing process"
                    pkill -f "$APP_HOME/$BACKEND_DIR/app.py" || true

                    echo "Copy the data from WORKDIR to Backend"
                    rsync -av "$WORKSPACE/aws-assignment/backend/" "$APP_HOME/$BACKEND_DIR"

                    echo "Install dependencies"
                    "$APP_HOME/$BACKEND_DIR/venv/bin/pip" install -r "$APP_HOME/$BACKEND_DIR/requirements.txt"

                    echo "Start the process"
                    echo $APP_HOME
                    echo $BACKEND_DIR
                    nohup /home/ubuntu/app/backend/venv/bin/python /home/ubuntu/app/backend/app.py > /home/ubuntu/app/backend/app.log 2>&1 &                    
                    
                    echo "Backend Started successfully"
                """
            }

        }



    }



}