pipeline {
    agent any 
    environment {
        APP_HOME = "/home/ubuntu/app"
        BACKEND_DIR = "backend"
        FRONTEND_DIR = "frontend"
    }

    stages{
        stage("Checkout"){
            steps {
                git(
                    url: "https://github.com/sanjay2028/ubuntu-tude-tude/",
                    branch: "jenkins"
                )
            }
        }

        stage("Virtual Env"){
            steps {
                sh """
                    echo "Switch to working dir"
                    cd /home/ec2-user/app/backend
                                        
                    python3 -m venv venv

                    ls -la > list.txt

                    . venv/bin/activate

                    deactivate
                """
            }
        }

        stage("Backend") {
            sh """
                echo "Copy data from workspace to backend"
                copy ${WORKSPACE}/aws-assignment/backend/* .
                echo "Copy Successful"

            """


        }
    }



}