FROM node:25.2-alpine

LABEL maintainer="Sanjay Kumar <sanjay2028@gmail.com>"

ENV HOST=0.0.0.0
ENV DANGEROUSLY_DISABLE_HOST_CHECK=true

WORKDIR /app

COPY ./frontend .

RUN npm install

EXPOSE 8000

CMD ["node", "index.js"]


